// <auto-generated/>
using HealthMate.Services.HttpServices.User.ForgotPassword.Confirm;
using HealthMate.Services.HttpServices.User.ForgotPassword.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace HealthMate.Services.HttpServices.User.ForgotPassword {
    /// <summary>
    /// Builds and executes requests for operations under \user\forgot-password
    /// </summary>
    public class ForgotPasswordRequestBuilder : BaseRequestBuilder {
        /// <summary>The confirm property</summary>
        public ConfirmRequestBuilder Confirm { get =>
            new ConfirmRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the HealthMate.Services.HttpServices.user.forgotPassword.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithUsernameItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("username", position);
            return new WithUsernameItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new ForgotPasswordRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForgotPasswordRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/forgot-password", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new ForgotPasswordRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ForgotPasswordRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user/forgot-password", rawUrl) {
        }
    }
}
