// <auto-generated/>
using HealthMate.Services.HttpServices.Symptoms.Details.Item;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace HealthMate.Services.HttpServices.Symptoms.Details {
    /// <summary>
    /// Builds and executes requests for operations under \symptoms\details
    /// </summary>
    public class DetailsRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the HealthMate.Services.HttpServices.symptoms.details.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithDiagnosis_ItemRequestBuilder this[int position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("diagnosis_id", position);
            return new WithDiagnosis_ItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>Gets an item from the HealthMate.Services.HttpServices.symptoms.details.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public WithDiagnosis_ItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("diagnosis_id", position);
            return new WithDiagnosis_ItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new DetailsRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/symptoms/details", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new DetailsRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DetailsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/symptoms/details", rawUrl) {
        }
    }
}
