// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace HealthMate.Services.HttpServices.Symptoms {
    public enum BodyPart {
        [EnumMember(Value = "head")]
        Head,
        [EnumMember(Value = "upperbody")]
        Upperbody,
        [EnumMember(Value = "lowerbody")]
        Lowerbody,
        [EnumMember(Value = "legs")]
        Legs,
        [EnumMember(Value = "arms")]
        Arms,
        [EnumMember(Value = "general")]
        General,
    }
}
