// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace HealthMate.Services.HttpServices.Symptoms {
    public enum Gender {
        [EnumMember(Value = "male")]
        Male,
        [EnumMember(Value = "female")]
        Female,
    }
}
